### ISSUE TITLE
Bump node from version 8 to 10

### ISSUE THREAD

**Issue by marechal-p** [eclipse-cdt/cdt-infra#37]
Node 8 is not maintained anymore, and new dependencies are requiring Node 10.

**Comment by jonahgraham** [comment]
Which version should we use.

We currently use Node 8 like this: https://github.com/eclipse-cdt/cdt-infra/blob/d2638faea3455f61646f7e3fd870eb7af37a1c3c/docker/cdt-infra-eclipse-full/ubuntu-18.04/Dockerfile#L38 - should this be node10 or go right to 12, the current LTS?

What does Theia use for build and deploy?

**Comment by marechal-p** [comment]
We're going for 12 with Theia. TBH I have no clue what's better between 10 and 12. My current thought is that it would be nicer to support versions as old as possible, and only bump when needed (since node versions are backward compatible but not forward compatible).
