### ISSUE TITLE
Remove CPP package from buildtools in Docker image

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt-infra#43]
See PR #42

**Comment by jonahgraham** [comment]
I will do this once Bug 568079 is resolved as if I remove it now, everyone's gerrits will fail until 568079 is done.

**Comment by T-Svensson** [comment]
> I will do this once Bug 568079 is resolved as if I remove it now, everyone's gerrits will fail until 568079 is done.

No, it's fine. The section is commented out as it did not work as expected. Feel free to merge and push!

**Comment by jonahgraham** [comment]
Thanks for reminding me it was commented out, I forgot.

**Comment by jonahgraham** [comment]
Done in df7ff26f3bf5da6ddc0a8f66eac3a1ee73375192 and image refs updated in 134f6b5beb0bcb6ff4b1836adda909faca63dfc0
